### ISSUE TITLE
Zap Upstream Links Broken

### ISSUE THREAD

**Issue by tajmone** [YunoHost/issues#2211]
The Zap repository has been archived, in the process the `zot` account was renamed to `zot-archive`, so all links need to be updated accordingly.

Original Zap link (as found in YunoHost documentation):

https://codeberg.org/zot/zap/

New link to archived repository:

https://codeberg.org/zot-archive/zap/

This might also apply to other tools by zot used in YunoHost.

I'm not submitting a PR for this since I don't know the codebase well enough to understand the ramifications of this URL change (e.g. if it affects installation scripts, or if the Zap app will be kept in the project now that it has reached EOL).

**Comment by tituspijean** [comment]
- [x] Zap: fixed by https://github.com/YunoHost-Apps/zap_ynh/pull/33
- [x] Osada: source already fixed by https://github.com/YunoHost-Apps/osada_ynh/commit/ffdebee52c608eda09d9e741f87295c70d092a27, but the manifest will also need to be updated to display the right repository
- [x] Hubzilla: uses Framagit as repository provider
