### ISSUE TITLE
Helpers 2.1 wishlist

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2403]
- Drop stupid legacy v0/v1 stuff like `__NAMETOREPLACE__` etc ... (some already done in bookworm maybe)
- Remove the need to pass --app=$app to ynh_app_settings_set/get (or is it already optional?)
- Rename `ynh_app_settings_get` to `ynh_settings_get` ?
- Add a `ynh_settings_set_default` or something to simplify the mess during upgrade with `if [[ -z "${foobar:-}" ]] ...`
- `--full_replace=1`  in `ynh_setup_source` should be `--full_replace` (cf trailing `=` in the `args_array` ...)
- replace stupid `0/1` by `false/true` in getopts ?
-Get rid of the boring "legacy args" mechanism in getopts (= positionals ? ... just enforce keyword args)
- rename the logging helpers ?
- homogenize options name such as `--service_name` vs `--service`, `--path` vs `--origin_path` etc
- backport most of the bookworm changes etc
- drop support for old .src format in ynh_setup_source ?

**Comment by Salamandar** [comment]
About app settings.
What is the use of 
```
    if [[ $key =~ (unprotected|protected|skipped)_ ]]; then
```
found at https://github.com/YunoHost/yunohost/blob/06dc3da3f4095d32b2846461e848be197f74da38/helpers/helpers.v1.d/setting#L21 ?

I can't find any settings with this name.

**Comment by alexAubin** [comment]
this is legacy stuff from the old permission system, it was cleaned up in bookworm

I'm working on a PR to backport most of the bookworm changes + other cleanups in a helpers 2.1 version

**Comment by Salamandar** [comment]
Fix the ynh_secure_remove clusterfuck about symlinks https://github.com/YunoHost/yunohost/pull/1716

**Comment by chri2** [comment]
> * Remove the need to pass --app=$app to ynh_app_settings_set/get (or is it already optional?)

I think it is already optional: https://github.com/YunoHost/yunohost/blob/06dc3da3f4095d32b2846461e848be197f74da38/helpers/helpers.v1.d/setting#L19

**Comment by Salamandar** [comment]
Here's a list of issues/prs we need to address :

- [x] https://github.com/YunoHost/yunohost/pull/1808 -> there might be some side effects, need to see what apps do (Edit by Aleks -> this is implemented in helpers 2.1)
- [ ] https://github.com/YunoHost/yunohost/pull/1840 -> some apps really need that (see https://github.com/YunoHost/issues/issues/1777 too)
- [ ] https://github.com/YunoHost/yunohost/pull/1849 -> cleanup !
- [ ] https://github.com/YunoHost/yunohost/pull/1870 -> cleanup too
- [ ] https://github.com/YunoHost/yunohost/pull/1882 -> helps decluttering the scripts
- [ ] https://github.com/YunoHost/yunohost/pull/1443 -> isn't that already fixed ? (Edit by Aleks : i guess it's implicitly fixed by using packaging v2?)
- [x] https://github.com/YunoHost/yunohost/pull/1716 -> this is a clusterfuck we reeeaaally need to fix. (see https://github.com/YunoHost/issues/issues/2253)
- [ ] https://github.com/YunoHost/yunohost/pull/1785 
- [x] https://github.com/YunoHost/issues/issues/826 -> a nice idea to declutter the upgrade script (Edit by Aleks: cf the new ynh_app_setting_set_default in helpers 2.1 which is automatically recommended by the patch script)
- [ ] https://github.com/YunoHost/issues/issues/2017 -> is it fixed? (Edit by Aleks: i guess no, there's some argument that `ynh_replace_special_string` should be the default)
- [ ] https://github.com/YunoHost/issues/issues/1696 -> i think it's Chrichri's version.
- [x] https://github.com/YunoHost/issues/issues/2307 -> we already cleaned that up a lot, we might be able to remove it completely from the helpers (Edit by Aleks: there's also a new helper something like `ynh_app_upstream_version_changed` to simplify the syntax, because i was too afraid of going down the road of removing the if entirely but at the same time i do agree that we should always regen the source / install dir)
- [ ] https://github.com/YunoHost/issues/issues/2364 (Edit by Aleks : hmpf this is a super special case where `uname -m` returns aarch64 but `dpkg --print-config` is armhf ... what the heck)
- [ ] https://github.com/YunoHost/issues/issues/2379 (Edit by Aleks: hmpf who really needs a secret longer than 200 chars -_-)
- [x] https://github.com/YunoHost/issues/issues/2243 is it fixed ? (Edit by Aleks: nope, but sounds indeed like something that should be fixed)

**Comment by alexAubin** [comment]
Closing because helpers 2.1 are sort of stabilized
